get_explore_api = "https://api.any-mate.com/v1/Api/MomentExplorePage"
get_last_post_api = "https://api.any-mate.com/v1/Api/MateMomentPage"
get_info_api1 = "https://api.any-mate.com/v1/Api/Mate/"
search_api = "https://api.any-mate.com/v1/Api/MateSearchPage"
login_api = "https://api.any-mate.com/v1/Api/Verification/0"
code_api = "https://api.any-mate.com/v1/Api/User/0"

get_login_token_api = "https://api.any-mate.com/v1/Api/UserHome"
check_in_api = "https://api.any-mate.com/v1/Api/CoinQuestUser/CreateOne/0"
upvote_api = "https://api.any-mate.com/v1/Api/EmojiVote/0"
get_mate_page = "https://api.any-mate.com/v1/Api/MatePage"